#!/usr/bin/env pwsh
# Backs up global Claude Code config into this repo:
#   ~/.claude/settings.json -> claude-home/settings.json
#   ~/.claude/skills/       -> claude-home/skills/
#   marketplaces + plugins  -> plugins.txt (replayable manifest)
# Honors CLAUDE_CONFIG_DIR if set (defaults to ~/.claude).
$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ClaudeHome = if ($env:CLAUDE_CONFIG_DIR) { $env:CLAUDE_CONFIG_DIR } else { Join-Path $HOME ".claude" }
$Dest = Join-Path $ScriptDir "claude-home"
$Manifest = Join-Path $ScriptDir "plugins.txt"

if (-not (Get-Command claude -ErrorAction SilentlyContinue)) {
    Write-Error "Error: 'claude' CLI not found in PATH."
    exit 1
}

New-Item -ItemType Directory -Force -Path $Dest | Out-Null

# --- settings.json ---
$SettingsSrc = Join-Path $ClaudeHome "settings.json"
$SettingsDst = Join-Path $Dest "settings.json"
if (Test-Path $SettingsSrc) {
    Copy-Item $SettingsSrc $SettingsDst -Force
    Write-Host "Backed up settings.json"
    if ((Get-Content $SettingsDst -Raw) -match '(?i)(api[_-]?key|secret|token|sk-[A-Za-z0-9])') {
        Write-Warning "claude-home/settings.json looks like it may contain secrets. Review it before committing!"
    }
} else {
    Remove-Item $SettingsDst -Force -ErrorAction SilentlyContinue
    Write-Host "No settings.json found at $ClaudeHome - skipped."
}

# --- skills/ ---
$SkillsSrc = Join-Path $ClaudeHome "skills"
$SkillsDst = Join-Path $Dest "skills"
if (Test-Path $SkillsSrc) {
    Remove-Item $SkillsDst -Recurse -Force -ErrorAction SilentlyContinue
    Copy-Item $SkillsSrc $SkillsDst -Recurse -Force
    $count = (Get-ChildItem $SkillsDst -Recurse -File).Count
    Write-Host "Backed up skills/ ($count files)"
} else {
    Remove-Item $SkillsDst -Recurse -Force -ErrorAction SilentlyContinue
    Write-Host "No skills directory found at $ClaudeHome - skipped."
}

# --- plugins manifest ---
$lines = @(
    "# Claude Code plugin manifest. Regenerated by backup.sh / backup.ps1 - do not edit by hand."
    "# Format: 'marketplace <name> <source>' and 'plugin <name@marketplace>'"
)

$marketplaces = claude plugin marketplace list --json | ConvertFrom-Json
foreach ($m in $marketplaces) {
    $source = $m.repo
    if ($m.source -eq "url") { $source = $m.url }
    elseif ($m.source -ne "github") { $source = $m.installLocation }
    $lines += "marketplace $($m.name) $source"
}

$plugins = claude plugin list --json | ConvertFrom-Json
foreach ($p in $plugins) {
    $id = $p.id
    if (-not $id) { $id = $p.pluginId }
    if (-not $id) { $id = "$($p.name)@$($p.marketplaceName)" }
    $lines += "plugin $id"
}

$lines | Set-Content $Manifest -Encoding utf8
Write-Host "Wrote $Manifest`:"
Get-Content $Manifest | ForEach-Object { Write-Host $_ }
Write-Host "Backup complete. Review the changes, then commit."
