#!/usr/bin/env bash
# Backs up global Claude Code config into this repo:
#   ~/.claude/settings.json -> claude-home/settings.json
#   ~/.claude/skills/       -> claude-home/skills/
#   marketplaces + plugins  -> plugins.txt (replayable manifest)
# Honors CLAUDE_CONFIG_DIR if set (defaults to ~/.claude).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_HOME="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
DEST="$SCRIPT_DIR/claude-home"
MANIFEST="$SCRIPT_DIR/plugins.txt"

command -v claude >/dev/null 2>&1 || { echo "Error: 'claude' CLI not found in PATH." >&2; exit 1; }
command -v jq >/dev/null 2>&1 || { echo "Error: 'jq' is required (e.g. 'brew install jq' or 'sudo apt install jq')." >&2; exit 1; }

mkdir -p "$DEST"

# --- settings.json ---
if [[ -f "$CLAUDE_HOME/settings.json" ]]; then
  cp "$CLAUDE_HOME/settings.json" "$DEST/settings.json"
  echo "Backed up settings.json"
  if grep -Eiq '(api[_-]?key|secret|token|sk-[A-Za-z0-9])' "$DEST/settings.json"; then
    echo "WARNING: claude-home/settings.json looks like it may contain secrets. Review it before committing!" >&2
  fi
else
  rm -f "$DEST/settings.json"
  echo "No settings.json found at $CLAUDE_HOME — skipped."
fi

# --- skills/ ---
if [[ -d "$CLAUDE_HOME/skills" ]]; then
  rm -rf "$DEST/skills"
  cp -R "$CLAUDE_HOME/skills" "$DEST/skills"
  echo "Backed up skills/ ($(find "$DEST/skills" -type f | wc -l) files)"
else
  rm -rf "$DEST/skills"
  echo "No skills directory found at $CLAUDE_HOME — skipped."
fi

# --- plugins manifest ---
{
  echo "# Claude Code plugin manifest. Regenerated by backup.sh / backup.ps1 — do not edit by hand."
  echo "# Format: 'marketplace <name> <source>' and 'plugin <name@marketplace>'"

  claude plugin marketplace list --json | jq -r '
    .[] | "marketplace \(.name) \(
      if .source == "github" then .repo
      elif .source == "url" then .url
      else .installLocation end)"'

  # `claude plugin list --json` prints an array of installed plugins (id = "name@marketplace").
  claude plugin list --json | jq -r '
    .[] | "plugin \(.id // .pluginId // "\(.name)@\(.marketplaceName)")"'
} > "$MANIFEST"

echo "Wrote $MANIFEST:"
cat "$MANIFEST"
echo "Backup complete. Review the changes, then commit."
